goSearcFirstIteration
drgi/tn-go-course pull request #3
Opened 2023-06-28 08:26 UTC by drgi

2023-06-28 21:29 UTC, DmitriyVTitov requested changes
Вы переусложняете программу. На Go надо писать просто, "топорно". Уберите всё лишнее, пишите код по минимуму.

2023-06-28 21:29 UTC, DmitriyVTitov commented on go-search/pkg/flags/flag.go
> +}
Это переусложнение не требуется. Флаг не обязателен по заданию.

2023-06-28 21:29 UTC, DmitriyVTitov commented on go-search/cmd/gosearch/app.go
> +}
Для чего, к примеру, эта функция? Для того, чтобы её вызвать однажды чуть выше. А читать код уже неудобно, приходится прыгать.

2023-06-28 21:29 UTC, DmitriyVTitov commented on go-search/cmd/gosearch/app.go
> +}
Уже ведь есть тип `crawler.Document`. Чем он вас не устроил? :)

2023-06-28 21:29 UTC, DmitriyVTitov commented on go-search/cmd/gosearch/app.go
> +	}
На мой взгляд, это чрезмерное усложнение. Не вижу необходимости в этом пакете.

2023-06-29 08:00 UTC, drgi commented on go-search/cmd/gosearch/app.go
> +}
Посчитал более удобным иметь структуру с результатом в таком виде, захотелось на выводе напечатать чуть больше данных: 
-количество документов, 
-кол-во отфильтрованных документов по слову, 
-готовый массив ссылок.
Поэтому слайса с crawler.Document не хватило)

2023-06-29 08:03 UTC, drgi commented on go-search/cmd/gosearch/app.go
> +}
Для того что бы не писать в if длинное условие, показалось более удобным работать в отдельной функции. Так же удобнее поменять эти условия. Но может и лишнее)

2023-06-29 08:10 UTC, DmitriyVTitov commented on go-search/cmd/gosearch/app.go
> +}
ОК, но я бы предпочёл минимальный код.

2023-06-29 08:10 UTC, DmitriyVTitov commented
Я отписался от уведомлений от репозитория, так что пишите через Тичбейз или Телеграм.

2023-07-05 06:39 UTC, closed without merging